services:
  - type: web
    name: ga-cash3-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true

cron:
  - name: update-ga-cash3
    schedule: '0 * * * *'  # hourly
    command: python scheduler.py
