name: Update GA Cash 3 Results

on:
  schedule:
    - cron: '50 16 * * *'  # 12:50 PM EDT (30m after Midday draw)
    - cron: '29 23 * * *'  # 11:29 PM UTC is 6:29 PM EDT (30m after Evening draw at 6:59pm -> 23:29 UTC)
    - cron: '04 04 * * *'  # 4:04 AM UTC (30m after Night draw at 11:34 PM EDT -> 04:04 UTC next day)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python update_csv.py

      - name: Commit & push if changed
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add data/ga_cash3_history.csv
          git diff --quiet --staged || git commit -m "🔄 Auto-update CSV with latest result"
          git push origin main
