name: Update GA Cash 3 Results

on:
  schedule:
    # 30 minutes after Midday (12:20 PM ET → 16:20 UTC +30m = 16:50 UTC)
    - cron: '50 16 * * *'
    # 30 minutes after Evening (6:59 PM ET → 22:59 UTC +30m = 23:29 UTC)
    - cron: '29 23 * * *'
    # 30 minutes after Night (11:34 PM ET → 03:34 UTC next day +30m = 04:04 UTC)
    - cron: '4 4 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch latest PDF
        run: python fetch_pdf.py

      - name: Prepare / update CSV
        run: python prepare_data.py

      - name: Commit and push if changed
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add data/ga_cash3_history.csv data/.status.json || true
          if ! git diff --staged --quiet; then
            git commit -m "🔄 Auto-update Cash3 CSV and status" 
            git push origin main
          else
            echo "No changes to commit."
          fi

  notify:
    needs: update
    if: always()  # run even if previous failed; adjust conditionally
    runs-on: ubuntu-latest
    steps:
      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          # These should be set as repository secrets:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: GA Cash3 Update Run - ${{ github.run_number }}
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: "noreply@yourdomain.com"
          body: |
            Workflow run: ${{ github.workflow }} (#${{ github.run_number }})
            Ref: ${{ github.ref }}
            Status: ${{ job.status }}
            Repository: ${{ github.repository }}
            View run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
