name: Update GA Cash 3 Results

on:
  schedule:
    - cron: '50 16 * * *'  # 12:20 PM ET +30m
    - cron: '29 23 * * *'  # 6:59 PM ET +30m
    - cron: '4 4 * * *'    # 11:34 PM ET +30m (next day UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If using snapshot script:
          pip install playwright
          playwright install

      - name: Fetch latest HTML snapshot
        run: python fetch_html_snapshot.py || echo "HTML snapshot failed; will fallback to PDF"

      - name: Update data and summary
        run: python prepare_data.py

      - name: Commit & push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/ga_cash3_history.csv data/summary.json
          git diff --quiet || git commit -m "🔄 Auto-update Cash3 data and summary" 
          git push

      - name: Optional notification
        run: echo "Update complete"
