name: Update GA Cash 3 Results

on:
  schedule:
    - cron: '50 16 * * *'  # Midday: 12:50 PM ET
    - cron: '30 23 * * *'  # Evening: 7:30 PM ET
    - cron: '5 4 * * *'    # Night: 12:05 AM ET
  workflow_dispatch:       # Allows manual run

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas beautifulsoup4 requests

      - name: Run update script
        run: python update_csv.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/ga_cash3_history.csv
          git commit -m "🔄 Auto-update CSV after draw" || echo "No changes"
          git push
