name: Update GA Cash3 Data

on:
  schedule:
    - cron: "50 16 * * *"  # 12:20pm ET +30m = 4:50pm UTC (Midday)
    - cron: "29 23 * * *"  # 6:59pm ET +30m = 11:29pm UTC (Evening)
    - cron: "4 4 * * *"    # 11:34pm ET +30m = 4:04am UTC next day (Night)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data preparation
        run: |
          python prepare_data.py

      - name: Commit and push updates
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/ga_cash3_history.csv data/summary.json || true
          if ! git diff --quiet --cached; then
            git commit -m "🔄 Auto-update Cash3 data and summary"
            git push
          else
            echo "No changes to commit."
          fi
